version: 2

sources:
  - name: destination_db
    description: "Raw data from the destination PostgreSQL database."
    database: destination_db
    schema: public
    tables:
      - name: films
        description: "List of films."
      - name: actors
        description: "List of actors."
      - name: film_actors
        description: "Mapping between films and actors."
        
models:
  - name: films
    description: "This table contains details about films."
    columns:
      - name: film_id
        description: "Unique identifier for the film."
        data_tests:
          - unique
          - not_null
      - name: title
        description: "Title of the film."
        data_tests:
          - not_null
      - name: release_date
        description: "Date the film was released."
        data_tests:
          - not_null
      - name: price
        description: "Price to buy a ticket."
        data_tests:
          - not_null
      - name: rating
        description: "The MPAA rating of the film."
        data_tests:
          - not_null
      - name: user_rating
        description: "Rating that users gave the film."
        data_tests:
          - not_null
      
  - name: actors
    description: "This table contains details about actors."
    columns:
      - name: actor_id
        description: "Unique identifier for the actor."
        data_tests:
          - unique
          - not_null
      - name: name
        description: "First name of the actor."


  - name: film_actors
    description: "This table maps films to the actors that starred in them."
    columns:
      - name: film_id
        description: "Identifier for the film."
        data_tests:
          - not_null
      - name: actor_id
        description: "Identifier for the actor."
        data_tests:
          - not_null
  
  
  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating for each film."
    columns:
      - name: film_id
        description: "The unique identifier for each film."
        data_tests:
          - unique
          - not_null

      - name: title
        description: "The title of the film."
        data_tests:
          - not_null

      - name: release_date
        description: "The release date of the film."
        data_tests:
          - not_null

      - name: price
        description: "The price of the film."
        data_tests:
          - not_null

      - name: rating
        description: "The MPAA rating of the film."

      - name: user_rating
        description: "The average user rating for the film."
        data_tests:
          - not_null

      - name: actor_count
        description: "The number of actors in the film."
        data_tests:
          - not_null

      - name: avg_actor_rating
        description: "The average rating of films that the actors of this film have acted in."
        data_tests:
          - not_null